# ===============================
# Project Info
# ===============================
sonar.projectKey=khatija-mern-10pshine
sonar.projectName=Khatija MERN 10PShine
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# ===============================
# Source Paths
# ===============================
sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# ===============================
# Coverage Reports (both sides)
# ===============================
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

# ===============================
# Exclusions
# ===============================
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/*.min.js,**/*.config.js,**/mocks/**,**/__tests__/**,**/test/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/*.min.js

# ===============================
# New Code Policy (internship)
# ===============================
sonar.newCode.referenceBranch=develop

# Authentication token for local SonarQube analysis
sonar.token=squ_553962adfd525de6cd271c8604328c9bb98736e4


sonar.nodejs.executable=C:\\Program Files\\nodejs\\node.exe

# ============================================================
#  END OF FILE
# ============================================================
